# Generated by Django 4.1.2 on 2023-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_userprofile_follower_delete_followingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_1',
            field=models.ImageField(default=1, upload_to='main_product'),
            preserve_default=False,
        ),
    ]
